logging:
 level:
  root: INFO
  org:
   springframework:
    security: DEBUG

server:
 port: 8090

management:
 endpoints:
  web:
   exposure:
    include: beans
 endpoint:
  enabled-by-default: true

database:
 db:
  host: localhost
  port: 5432
  username: richard
  password: test123

security:
 oauth2:
  resource:
   tokenInfoUri: http://localhost:8090/oauth/check_token
