logging:
 level:
  root: INFO
  org:
   springframework: INFO
management:
 endpoints:
  web:
   exposure:
    include: beans
 endpoint:
  enabled-by-default: true

spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  platform: postgres
  url: jdbc:postgresql://localhost:5432/users
  username: richard
  password: test123
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true



#security:
# user:
#  name: root
#  password: test123
# oauth2:
#  client:
#   client_id: richard
#   client-secret: meinPasswort123
#   scope: read