logging:
 level:
  root: INFO
  org:
   springframework:
    security: DEBUG

management:
 endpoints:
  web:
   exposure:
    include: beans
 endpoint:
  enabled-by-default: true

spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  platform: postgres
  url: jdbc:postgresql://localhost:5432/users
  username: richard
  password: test123
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  generate-ddl: true



security:
 oauth2:
  client:
   client_id: richard
   client-secret: meinPasswort123
   accessTokenUri: http://localhost:8080/oauth/token
   userAuthorizationUri: http://localhost:8080/oauth/authorize