logging:
 level:
  root: INFO
  org:
   springframework:
    security: DEBUG

server:
 port: 8090

management:
 endpoints:
  web:
   exposure:
    include: beans
 endpoint:
  enabled-by-default: true

database:
 db:
  host: localhost
  port: 5432
  username: richard
  password: test123
#spring:
# datasource:
#  driver-class-name: org.postgresql.Driver
#  platform: postgres
#  url: jdbc:postgresql://localhost:5432/users
#  username: richard
#  password: test123
# jpa:
#  database-platform: org.hibernate.dialect.PostgreSQLDialect
#  generate-ddl: true
